# Change these first
owner: CalamityJames # Your GitHub organization or username, where this repository lives
repo: BCL-status # The name of this repository

sites:
  - name: RHS CrewLink Voice Server
    url: https://rhs-crewlink.herokuapp.com

assignees:
  - CalamityJames

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /BCL-status
  logoUrl: https://github.com/CalamityJames/BetterCrewLink/raw/nightly-calamityjames/src/renderer/logos/BCL-AppIcon.png
  favicon: https://github.com/CalamityJames/BetterCrewLink/raw/nightly-calamityjames/src/renderer/logos/BCL-AppIcon.png
  faviconSvg: https://github.com/CalamityJames/BetterCrewLink/raw/nightly-calamityjames/src/renderer/logos/BCL-AppIcon.svg
  name: CJ BetterCrewLink Status
  introTitle: "BetterCrewLink's status page"
  introMessage: A status site for the RHS Crewlink server
  navbar:
    - title: Status
      href: /BCL-status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
